INTEXGroup3-7/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace INTEXGroup3_7.Models
{
    public class Order
    {
        [Key]
        public int transaction_ID { get; set; }

        [ForeignKey("Customer")]
        public int customer_ID { get; set; }
        public Customer Customer { get; set; }

        public DateOnly date { get; set; }

        public string day_of_week { get; set; }

        public int time { get; set; }

        public string entry_mode { get; set; }

        public int amount { get; set; }

        public string type_of_transaction { get; set; }

        public string country_of_transaction { get; set; }
        
        public string shipping_address { get; set; }

        public string bank { get; set; }
        
        public string type_of_card { get; set; }
        
        public bool fraud { get; set; }
    }
}

INTEXGroup3-7/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace INTEXGroup3_7.Models;

public class Product
{
    [Key]
    public int product_ID { get; set; }
    public string name { get; set; }
    public int year { get; set; }
    
    public int num_parts { get; set; }
    public int price { get; set; }
    
    public string img_link { get; set; }
    public string primary_color { get; set; }
    
    public string? secondary_color { get; set; }
    
    public string description { get; set; }
    public string category { get; set; }
    
    public string? subcategory { get; set; }
}

INTEXGroup3-7/Models/ViewModels/ProductsViewModel.cs
namespace INTEXGroup3_7.Models.ViewModels;

public class ProductsViewModel
{
    public IQueryable<Product> Products { get; set; }
    public PaginationInfo PaginationInfo { get; set; } = new PaginationInfo();
    public string[]? CurrentProductColors { get; set; }
    
    public string[]? CurrentProductCategories { get; set; }
    
    public int? CurrentProductNumber { get; set; }
}

INTEXGroup3-7/Components/CartListDisplayViewComponent.cs
using INTEXGroup3_7.Models;
using Microsoft.AspNetCore.Mvc;

using INTEXGroup3_7.Models;
using Microsoft.AspNetCore.Mvc;
using INTEXGroup3_7.Models.ViewModels;


namespace INTEXGroup3_7.Components
{
    public class CartListDisplayViewComponent : ViewComponent
    {
        private Cart cart;
        public Order order;

        public CartListDisplayViewComponent(Cart cartService)
        {
            this.cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            var data = new CheckoutOrderViewModel
            {
                Cart = cart,

                Order = order
            };
            return View(data);
        }
    }

}

INTEXGroup3-7/Components/CartSummaryViewComponent.cs
using INTEXGroup3_7.Models;
using Microsoft.AspNetCore.Mvc;

namespace INTEXGroup3_7.Components;

public class CartSummaryViewComponent : ViewComponent
{
    private Cart cart;

    public CartSummaryViewComponent(Cart cartService)
    {
        this.cart = cartService;
    }

    public IViewComponentResult Invoke()
    {
        return View(cart);
    }
}

INTEXGroup3-7/Components/ProductTypesViewComponent.cs
using INTEXGroup3_7.Models;
using Microsoft.AspNetCore.Mvc;
using INTEXGroup3_7.Models.ViewModels;

namespace INTEXGroup3_7.Components;

public class ProductTypesViewComponent : ViewComponent
{
    private IAmazonRepository _Repo;
    
    public ProductTypesViewComponent(IAmazonRepository temp)
    {
        _Repo = temp;
    }

    public IViewComponentResult Invoke()
    {
        
        var productColors = _Repo.Products
            .Select(x => x.primary_color)
            .Distinct()
            .OrderBy(x => x)
            .ToList();

        var productCategories = _Repo.Products
            .Select(x => x.category)
            .Distinct()
            .OrderBy(x => x)
            .ToList();

        var ProductTypes = new ProductFilterViewModel()
        {
            Colors = productColors,
            Category = productCategories
        };

        return View(ProductTypes);
    }
}

INTEXGroup3-7/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using INTEXGroup3_7.Models;
using INTEXGroup3_7.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using System.Security.Cryptography.Xml;

namespace INTEXGroup3_7.Controllers;

public class HomeController : Controller
{
    private IAmazonRepository _repo;
    private InferenceSession _session;

    public HomeController(IAmazonRepository temp)
    {
        _repo = temp;
        // bring in Onnx prediction model
        _session = new InferenceSession(
            "fraud_model.onnx");
    }

    public IActionResult Index()
    {
        var top_products = _repo.TopProducts.Select(tp => tp.product_ID);
        var rec_products = _repo.Products
            .Where(p => top_products.Contains(p.product_ID))
            .Take(8)
            .ToList();

        var id = 1;

        var user_rec = _repo.UserRecommendations.FirstOrDefault(x => x.customer_ID == id);

        var recProductNames = new List<string> 
        { 
            user_rec?.rec1, user_rec?.rec2, user_rec?.rec3, user_rec?.rec4, user_rec?.rec5
        };

        var groupProducts = _repo.Products.Where(x => recProductNames.Contains(x.name)).ToList();

        var data = new HomePageViewModel()
        {
            Products = rec_products,
            
            GroupOfProducts = groupProducts
            
        };
            
        return View(data);
    }
    
    public IActionResult About()
    {
        return View();
    }
    
    public IActionResult Shop(int pageNum, int productNum, string[] selectedColors, string[] selectedCategories)
    {
        int pageSize = 6;
        
        if (productNum != 0 && productNum != null)
        {
            pageSize = productNum;
        }

        string[] colorsList = selectedColors;
        string[] categoryList = selectedCategories;

        ViewBag.selectedColors = colorsList;
        ViewBag.selectedColors = categoryList;
        
        // Get all products if no colors are selected
        var query = _repo.Products.AsQueryable();
        
        // Filter products by selected categories
        if (selectedCategories != null && selectedCategories.Any())
        {
            query = query.Where(p => selectedCategories.Contains(p.category));
        }
        
        // Filter products by selected colors
        if (colorsList != null && selectedColors.Any())
        {
            query = query.Where(p => selectedColors.Contains(p.primary_color));
        }

        var data = new ProductsViewModel()
        {
            Products = query
                .OrderBy(x => x.name)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),
            
            PaginationInfo = new PaginationInfo
            {
                CurrentPage = pageNum,
                ItemsPerPage = pageSize,
                TotalItems = query.Count()
            },
            CurrentProductColors = colorsList,
            CurrentProductCategories = categoryList,
            CurrentProductNumber = productNum
        };
        
        return View(data);
    }
    
    [Authorize(Roles = "Admin, Customer")]
    [HttpGet]
    public IActionResult Checkout()
    {
    
        return View(new CheckoutOrderViewModel());
    }
    public IActionResult Product(int product_ID)
    {
        var id = product_ID;

        var rec_data = _repo.ItemRecommendations.FirstOrDefault(x => x.product_ID == id);

        var recProductIds = new List<int?> 
        { 
            rec_data?.rec1, rec_data?.rec2, rec_data?.rec3, rec_data?.rec4, rec_data?.rec5, 
            rec_data?.rec6, rec_data?.rec7, rec_data?.rec8, rec_data?.rec9, rec_data?.rec10 
        }.Select(x => x + 1);;

        var groupProducts = _repo.Products.Where(x => recProductIds.Contains(x.product_ID)).ToList();

        var data = new ProductRecommendationViewModel()
        {
            Product = _repo.Products.FirstOrDefault(x => x.product_ID == id),
            GroupProducts = groupProducts
        };
        
        return View(data);
    }
    
    public IActionResult Privacy()
    {
        
        return View();
    }

    [Authorize(Roles = "Admin")]
    public IActionResult Admin()
    {
        var prod_data = _repo.Products.AsQueryable();

        var order_data = _repo.Orders.AsQueryable();

        var customer_date = _repo.Customers.AsQueryable();

        var user_data = _repo.Users.AsQueryable();


        var databaseData = new DatabaseModel()
        {
            Products = prod_data
                .OrderBy(x => x.product_ID),

            Orders = order_data
                .OrderByDescending(x => x.date)
                .Take(50),
            
            Users = user_data
            
        };
        
        return View(databaseData);
    }
    
    [HttpGet]
    public IActionResult AddOrder()
    {
        return View(new Order());
    }

    [HttpPost]
    public IActionResult AddOrder(Order model)
    {
        if (ModelState.IsValid)
        {
            // Create an Order entity from the view model
            var order = new Order
            {
                customer_ID = model.customer_ID,
                date = model.date,
                day_of_week = model.day_of_week,
                time = model.time,
                entry_mode = model.entry_mode,
                amount = model.amount,
                type_of_transaction = model.type_of_transaction,
                country_of_transaction = model.country_of_transaction,
                shipping_address = model.shipping_address,
                bank = model.bank,
                type_of_card = model.type_of_card,
                fraud = model.fraud
            };
            // Save the order to the database using the repository
            _repo.AddOrder(order);
            return RedirectToAction("OrderConfirmed");
        }
        else
        {
            return Redirect("OrderPending");
        }
    }
    
    [Authorize(Roles = "Admin")]
    public IActionResult OrderView(int id)
    {
        var recordToEdit = _repo.Orders
            .Include(o => o.Customer)
            .Single(x => x.transaction_ID == id);
        
        return View(recordToEdit);
    }

    [Authorize(Roles = "Admin")]
    [HttpGet]
    public IActionResult AddProduct()
    {
        ViewBag.PrimaryColors = _repo.Products
            .Select(p => p.primary_color) // Select the primary_color property
            .Distinct() // Get distinct values
            .OrderBy(color => color) // Order the distinct values
            .ToList(); // Convert to List

        ViewBag.SecondaryColors = _repo.Products
            .Select(p => p.secondary_color) // Select the secondary color property
            .Distinct() // Get distinct values
            .OrderBy(seccolor => seccolor) // Order the distinct values
            .ToList(); // Convert to List

        ViewBag.Categories = _repo.Products
            .Select(p => p.category) // Select the category property
            .Distinct() // Get distinct values
            .OrderBy(category => category) // Order the distinct values
            .ToList(); // Convert to List

        ViewBag.SubCategories = _repo.Products
            .Select(p => p.subcategory) // Select the subcategory property
            .Distinct() // Get distinct values
            .OrderBy(subcategory => subcategory) // Order the distinct values
            .ToList(); // Convert to List

        return View(new Product());
    }
    

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public IActionResult AddProduct(Product response)
    {
        if (ModelState.IsValid)
        {
            _repo.AddProductItem(response);

            return Redirect("Admin");
        }
        else
        {
            return View(response);
        }
    }
    
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public IActionResult ProductItemEdit(int id)
    {
        var recordToEdit = _repo.Products
            .Single(x => x.product_ID == id);

        ViewBag.PrimaryColors = _repo.Products
            .Select(p => p.primary_color) // Select the primary_color property
            .Distinct() // Get distinct values
            .OrderBy(color => color) // Order the distinct values
            .ToList(); // Convert to List

        ViewBag.SecondaryColors = _repo.Products
            .Select(p => p.secondary_color) // Select the secondary color property
            .Distinct() // Get distinct values
            .OrderBy(seccolor => seccolor) // Order the distinct values
            .ToList(); // Convert to List

        ViewBag.Categories = _repo.Products
            .Select(p => p.category) // Select the category property
            .Distinct() // Get distinct values
            .OrderBy(category => category) // Order the distinct values
            .ToList(); // Convert to List

        ViewBag.SubCategories = _repo.Products
            .Select(p => p.subcategory) // Select the subcategory property
            .Distinct() // Get distinct values
            .OrderBy(subcategory => subcategory) // Order the distinct values
            .ToList(); // Convert to List

        return View(recordToEdit);
    }
    
    [Authorize(Roles = "Admin")]
    [HttpPost]
    public IActionResult ProductItemEdit(Product product)
    {
        _repo.UpdateProductItem(product);
        return Redirect("Admin");
    }
    
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public IActionResult ProductItemDelete(int id)
    {
        var recordToEdit = _repo.Products
            .Single(x => x.product_ID == id);
        return View(recordToEdit);
    }
    
    [Authorize(Roles = "Admin")]

INTEXGroup3-7/Views/Home/AddProduct.cshtml
@{

}
@model Product

<section class="py-md-0">
    <div class="image image-overlay" style="background-image:url(/images/vault.jpg)"></div>
    <div class="container">
        <div class="row justify-content-center align-items-center vh-md-100">
            <div class="col-md-10 col-lg-5">
                <div class="accordion accordion-portal" id="accordionExample">
                    <div class="card active">
                        <form method="post">
                        <div class="card-header" id="headingOne">
                            <h2 class="mb-0">
                                <a asp-controller="Home" asp-action="Admin">
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            Add New Product
                                    </button>
                                </a>
                            </h2>
                        </div>

                        <div class="row mt-2">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="hidden" asp-for="product_ID"/>
                                </div>
                                <div class="form-group">
                                    <label asp-for="name">Name</label>
                                    <input asp-for="name" class="form-control" value="@Model.name">
                                </div>
                                <div class="form-group">
                                    <label asp-for="year">Year</label>
                                    <input asp-for="year" class="form-control" value="@Model.year">
                                </div>
                                <div class="form-group">
                                    <label asp-for="num_parts">Number of Parts</label>
                                    <input asp-for="num_parts" class="form-control" value="@Model.num_parts">
                                </div>
                                <div class="form-group">
                                    <label asp-for="price">Price</label>
                                    <input asp-for="price" class="form-control" value="@Model.price">
                                </div>
                                <div class="form-group">
                                    <label asp-for="img_link">Image Link</label>
                                    <input asp-for="img_link" class="form-control" value="@Model.img_link">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="primary_color">Primary Color</label>
                                        <select asp-for="primary_color" class="form-control">
                                            <option value="@Model.primary_color">Select a color</option>
                                            @foreach (var color in ViewBag.PrimaryColors)
                                            {
                                                <option value="@color">@color</option>
                                            }
                                        </select>
                                        
                                </div>
                                <div class="form-group">
                                    <label asp-for="secondary_color">Secondary Color</label>
                                        <select asp-for="secondary_color" class="form-control">
                                            <option value="@Model.secondary_color">Select a color</option>
                                            @foreach (var seccolor in ViewBag.SecondaryColors)
                                            {
                                                <option value="@seccolor">@seccolor</option>
                                            }
                                        </select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="category">Category</label>
                                    <select asp-for="category" class="form-control">
                                        <option value="@Model.category">@Model.category</option>
                                        @foreach (var cat in ViewBag.Categories)
                                        {
                                            <option value="@cat">@cat</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="subcategory">Subcategory</label>
                                    <select asp-for="subcategory" class="form-control">
                                        <option value="@Model.subcategory">@Model.subcategory</option>
                                        @foreach (var subcat in ViewBag.SubCategories)
                                        {
                                            <option value="@subcat">@subcat</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="description">Description</label>
                                    <input asp-for="description" class="form-control" value="@Model.description">
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-block btn-primary"><a>Add</a></button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

INTEXGroup3-7/Views/Home/Checkout.cshtml
@{
}
@model CheckoutOrderViewModel
<!-- hero -->
<section>
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <h1>Checkout</h1>
      </div>
    </div>
  </div>
</section>

<vc:cart-list-display />
      

INTEXGroup3-7/Views/Home/LoginStyle.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
  <title>@ViewData["Title"] - INTEXGroup3_7</title>
  <link rel="stylesheet" href="/css/vendor.css" asp-append-version="true"/>
  <link rel="stylesheet" href="/css/style.css" asp-append-version="true"/>
</head>
<body>
<!-- header -->
<header class="header header-dark bg-dark header-sticky separator-bottom">
  <div class="container">
    <div class="row">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a href="" class="navbar-brand order-1 order-lg-2"><img src="/images/logo.svg" alt="Logo"></a>
        <button class="navbar-toggler order-2" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-3 order-lg-1" id="navbarMenu">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="About">About</a></li>
            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Shop" asp-route-pageNum="1">Shop</a></li>
          </ul>
        </div>
        <vc:cart-summary />
      </nav>
    </div>
  </div>
</header>

<!-- footer -->
<footer class="bg-dark text-white py-4 position-relative overflow-hidden">
  <div class="position-absolute start-0 top-0 w-100 opacity-6" style="margin-top: -40px;">
    <img src="/images/waves-white.svg" alt="pattern-lines" class="w-100 h-100 opacity-6">
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-3 text-center">
        <p>Copyright &copy; 2024 - Team 3-7</p>
      </div>
      <div class="col-1"></div> <!-- Added an empty column for spacing -->
      <div class="col-6 text-center">
        <a class="mr-3" asp-controller="Home" asp-action="Index">Home</a>
        <a class="mr-3" asp-controller="Home" asp-action="About">About</a>
        <a class="mr-3" asp-controller="Home" asp-action="Shop">Shop</a>
        <a asp-controller="Home" asp-action="Privacy">Privacy</a>
      </div>
    </div>
  </div>
</footer>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/js/site.js" asp-append-version="true"></script>
<script src="/js/vendor.min.js"></script>
<script src="/js/app.js"></script>
</body>
</html>

INTEXGroup3-7/Views/Home/OrderConfirmed.cshtml
@{
    
}
@model Order

<!-- welcome -->
<section class="hero">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-md-6">
                <h1 class="font-weight-light"><b class="d-block">Order Confirmed!</b></h1>
            </div>
        </div>
        <div class="row gutter-4">
            <div class="col-md-5 col-lg-4">
                <span class="eyebrow">Order</span>
                <p class="lead my-1 text-dark">Transaction ID: @Model.transaction_ID <br>Amount: @Model.amount<br>Shipping Address: @Model.shipping_address</p>
                <a asp-controller="Home" asp-action="Index" class="eyebrow underline action">Go Back</a>
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
</section>

INTEXGroup3-7/Views/Home/OrderPending.cshtml
@{
}

<!-- welcome -->
<section class="hero">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-md-6">
                <h1 class="font-weight-light"><b class="d-block">Order Pending!</b></h1>
            </div>
        </div>
        <div class="row gutter-4">
            <div class="col-md-5 col-lg-4">
                <span class="eyebrow">Your Order Is Currently Under Review</span>
                <p class="lead my-1 text-dark">Thanks for your patience. We will get back to you soon.<br><br></p>
                <a asp-controller="Home" asp-action="Index" class="eyebrow underline action">Go Back</a>
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
</section>

INTEXGroup3-7/Views/Home/ProductItemDelete.cshtml
@{

}
@model Product

<section class="py-md-0">
    <div class="image image-overlay" style="background-image:url(/images/vault.jpg)"></div>
    <div class="container">
        <div class="row justify-content-center align-items-center vh-md-100">
            <div class="col-md-10 col-lg-5">
                <div class="accordion accordion-portal" id="accordionExample">
                    <div class="card active">
                        <form method="post">
                            <input type="hidden" asp-for="product_ID">
                            <div class="card-header" id="headingOne">
                                <h2 class="mb-0">
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Delete Product
                                    </button>
                                </h2>
                            </div>
                            <div style="margin-bottom: 20px">
                                <h4>Do you really want to delete: <br/>@Model.name</h4>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-block btn-danger"><a>Delete</a></button>
                                <button class="btn btn-block btn-primary" asp-controller="Home" asp-action="Admin"><a>Cancel</a></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

INTEXGroup3-7/Views/Home/Shop.cshtml
@{
  ViewData["Title"] = "Shop";
}
@model ProductsViewModel

<!-- header -->
<section class="hero hero-small">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <h1 class="mb-0">Shop</h1>
        <nav aria-label="breadcrumb">
          <p>Aurora's Favorite Lego Sets</p>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- listing -->
<section class="pt-0">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="row gutter-1 gutter-md-2 align-items-center">
          <div class="col-md-6">
            <span class="eyebrow">@Model.PaginationInfo.TotalItems products</span>
          </div>
          <div class="col-md-6 text-md-right">
            <div class="btn-group" role="group" aria-label="Basic example">
              <div class="dropdown">
                <a class="btn btn-outline-secondary btn-sm dropdown-toggle" href="#!" role="button" id="dropdownMenuLink-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Products Displayed
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink-3">
                  <a class="dropdown-item" asp-controller="Home" asp-action="Shop" asp-route-productNum="5">5 Products</a><br/>
                  <a class="dropdown-item" asp-controller="Home" asp-action="Shop" asp-route-productNum="10">10 Products</a><br/>
                  <a class="dropdown-item" asp-controller="Home" asp-action="Shop" asp-route-productNum="20">20 Products</a>
                </div>
              </div>
              <button data-toggle="modal" data-target="#filter" type="button" class="btn btn-sm btn-outline-secondary">Filter</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">

      <!-- content -->
      <div class="col">
        <div class="row gutter-2 gutter-lg-3">
          @foreach (Product p in Model.Products)
          {
            <partial name="ProductSummary" model="p"/>
          }
        </div>
        <div class="row">
          <div class="col">
            <nav class="d-inline-block">
              <div page-model="@Model.PaginationInfo" page-action="Shop" page-class-enabled="true"
                   page-class="page-link" page-class-normal="page-item" page-class-selected="page-item active" page-url-selectedColors="@Model.CurrentProductColors" page-url-productNum="@Model.CurrentProductNumber" page-url-selectedCategories="@Model.CurrentProductCategories" class="pagination"></div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <vc:product-types />
</section>