INTEXGroup3-7/Models/Cart.cs
using System.Diagnostics.Metrics;

namespace INTEXGroup3_7.Models;

public class Cart
{
    public List<CartLine> Lines { get; set; } = new List<CartLine>();

    public virtual void AddItem(Product prod, int quantity)
    {
        CartLine? line = Lines
            .Where(x => x.Product.product_ID == prod.product_ID)
            .FirstOrDefault();
        
        //Has this item already been added to our cart?
        if (line == null)
        {
            Lines.Add(new CartLine()
            {
                Product = prod,
                Quantity = quantity
            });
        }
        else
        {
            line.Quantity += quantity;
        }
    }
    
    public virtual void UpdateItem(Product prod, int quantity)
    {
        CartLine? line = Lines
            .Where(x => x.Product.product_ID == prod.product_ID)
            .FirstOrDefault();
        
        //Has this item already been added to our cart?
        if (line == null)
        {
            Lines.Add(new CartLine()
            {
                Product = prod,
                Quantity = quantity
            });
        }
        else
        {
            line.Quantity = quantity;
        }
    }

    public virtual void RemoveLine(Product prod) => Lines.RemoveAll(x => x.Product.product_ID == prod.product_ID);

    public virtual void Clear() => Lines.Clear();

    public decimal CalculateTotal() => Lines.Sum(x => x.Product.price * x.Quantity);

    public decimal CalculateTotalItems() => Lines.Count();
    public class CartLine
    {
        public int CartLineId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
        
    }
}

INTEXGroup3-7/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using INTEXGroup3_7.Models;
using INTEXGroup3_7.Infrastructure;

namespace INTEXGroup3_7.Pages;

public class CartModel : PageModel
{
    private IAmazonRepository _repo;
    
    public Cart Cart { get; set; }

    public CartModel(IAmazonRepository temp, Cart cartService)
    {
        _repo = temp;
        Cart = cartService;
    }
    public string ReturnUrl { get; set; } = "/";
    
    public void OnGet(string returnUrl)
    {
        ReturnUrl = returnUrl ?? "/";
    }

    public IActionResult OnPost(int product_ID, string returnUrl)
    {
        Product prod = _repo.Products
            .FirstOrDefault(x => x.product_ID == product_ID);

        if (prod != null)
        {
            Cart.AddItem(prod, 1);
        }

        return RedirectToPage (new {returnUrl = returnUrl});
    }

    public IActionResult OnPostRemove(int product_ID, string returnUrl)
    {
        Cart.RemoveLine(Cart.Lines.First(x => x.Product.product_ID == product_ID).Product);
        
        return RedirectToPage (new {returnUrl = returnUrl});
    }
    
    public IActionResult OnPostUpdate(int product_ID, string returnUrl, int quantity)
    {
        Product prod = _repo.Products
            .FirstOrDefault(x => x.product_ID == product_ID);

        if (prod != null)
        {
            Cart.UpdateItem(prod, quantity);
        }

        return RedirectToPage (new {returnUrl = returnUrl});
    }
}

INTEXGroup3-7/Pages/Cart.cshtml
@page
@model INTEXGroup3_7.Pages.CartModel

@{
}
<!-- hero -->
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        @if (Model.Cart.CalculateTotalItems() == 0)
        {
          <h1 class="font-weight-light"><b class="d-block">Your Cart Is Empty</b></h1>
          <img src="images/emptycart.jpg" style="max-height: 400px; margin-top: 20px;"/>
          <div>
            <a class="btn btn-outline-primary" style="margin-top: 40px;" asp-controller="Home" asp-action="Shop" asp-route-pageNum="1">Continue Shopping</a>
          </div>
        }
        else
        {
          <h1>Your Cart</h1>
        }
      </div>
    </div>
  </div>
</section>

@if (Model.Cart.CalculateTotalItems() != 0)
{
  <section class="pt-0">
    <div class="container">
      <div class="row mb-1 d-none d-lg-flex">
        <div class="col-lg-8">
          <div class="row pr-6">
            <div class="col-lg-6"><span class="eyebrow">Product</span></div>
            <div class="col-lg-2 text-center"><span class="eyebrow">Price</span></div>
            <div class="col-lg-2 text-center"><span class="eyebrow">Quantity</span></div>
            <div class="col-lg-2 text-center"><span class="eyebrow">Total</span></div>
          </div>
        </div>
      </div>
      <div class="row gutter-2 gutter-lg-4 justify-content-end">
        <div class="col-lg-8 cart-item-list">

          <!-- cart item -->
          @foreach (var l in Model.Cart?.Lines ?? Enumerable.Empty<Cart.CartLine>())
          {
            <div class="cart-item">
              <div class="row align-items-center" style="margin-top: 25px;">
                <div class="col-12 col-lg-6">
                  <div class="media media-product">
                    <a asp-controller="Home" asp-action="Product" asp-route-product_ID="@l.Product.product_ID"><img src="@l.Product.img_link" alt="Image-@l.Product.product_ID" style="max-height: 100px;"></a>
                    <div class="media-body">
                      <h5 class="media-title">@l.Product.name</h5>
                      <span class="small">@l.Product.primary_color</span>
                    </div>
                  </div>
                </div>
                <div class="col-4 col-lg-2 text-center">
                  <span class="cart-item-price">@l.Product.price.ToString("c")</span>
                </div>
                <div class="col-4 col-lg-2 text-center">
                   <!-- <div class="counter"> -->
                    <form asp-page-handler="Update" method="post">
                      <input type="hidden" name="product_ID" value="@l.Product.product_ID"/>
                      <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl"/>
                      
                      <!-- <span class="counter-minus icon-minus" field='qty-@l.Product.product_ID'></span> -->
                      <span type='text' name='qty-@l.Product.product_ID' id="quantity" class="counter-value" min="1" max="10">@l.Quantity</span>
                      <!-- <span class="counter-plus icon-plus" field='qty-@l.Product.product_ID'></span> -->
                     </form>
                  <!-- </div> -->
                </div>
                <div class="col-4 col-lg-2 text-center">
                  <span class="cart-item-price">@((l.Quantity * l.Product.price).ToString("c"))</span>
                </div>
                <form asp-page-handler="Remove" method="post">
                  <input type="hidden" name="product_ID" value="@l.Product.product_ID"/>
                  <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl"/>
                  <button type="submit" style="border: none; background: none;">
                    <a class="cart-item-close"><i class="icon-x"></i></a>
                  </button>
                </form>
              </div>
            </div>
          }
        </div>

        <div class="col-lg-4">
          <div class="card card-data bg-light">
            <div class="card-header py-2 px-3">
              <div class="row align-items-center">
                <div class="col">
                  <h3 class="fs-18 mb-0">Order Summary</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-minimal">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  Subtotal
                  <span>@Model.Cart?.CalculateTotal().ToString("c")</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  Shipping
                  <span>Free</span>
                </li>
              </ul>
            </div>
            <div class="card-footer py-2">
              <ul class="list-group list-group-minimal">
                <li class="list-group-item d-flex justify-content-between align-items-center text-dark fs-18">
                  Total
                  <span>@Model.Cart?.CalculateTotal().ToString("c")</span>
                </li>
              </ul>
            </div>
          </div>
          <a class="btn btn-lg btn-block btn-outline-primary" style="margin-top: 10px;" href="@Model.ReturnUrl">Continue Shopping</a>
          <a class="btn btn-lg btn-primary btn-block mt-1" asp-controller="Home" asp-action="Checkout">Checkout</a>
        </div>
      </div>
    </div>
  </section>
}